version: '3'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 8080:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus/data
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - cadvisor
      - node-exporter
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    deploy:
      mode: global
    restart: unless-stopped
    ports:
      - 8081:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    deploy:
      mode: global
    restart: unless-stopped
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 8082:3000
    volumes:
    - grafana_data:/var/lib/grafana
    - grafana_plugins:/var/lib/grafana/plugins
    - ./certs:/etc/ssl/cert/
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=P4ssW0rd0!
      - VIRTUAL_PROTO=https
      - GF_SERVER_CERT_FILE=/etc/ssl/cert/home.crt
      - GF_SERVER_CERT_KEY=/etc/ssl/cert/home.key
      - GF_SERVER_PROTOCOL=https
    depends_on:
      - prometheus
      - cadvisor
      - node-exporter
  nginx:
    image: nginx:latest
    container_name: reverse_proxy
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:rw
    - ./certs/:/etc/ssl/
    - ./secrets:/etc/secrets/
    restart: unless-stopped
    ports:
    - 8084:443

volumes:
  data:
  grafana_data:
  grafana_plugins:
